postit/config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new' #for SEO - includes new
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :users, only: [:create]

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end

  resources :categories, only: [:new, :create]
end

postit/app/models/category.rb
class Category < ActiveRecord::Base;
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true
end

postit/app/models/comment.rb
class Comment < ActiveRecord::Base;
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post
  validates :body, presence: true
end

postit/app/models/post.rb
class Post < ActiveRecord::Base;
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
end

postit/app/models/post_category.rb
class PostCategory < ActiveRecord::Base;
  belongs_to :post
  belongs_to :category
end

postit/app/models/user.rb
class User < ActiveRecord::Base;
  has_many :posts
  has_many :comments

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: { minimum: 3 }

end

postit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = "Must be logged in to do that."
      redirect_to root_path
    end
  end
end

postit/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "You have created a new category"
      redirect_to root_path
    else
      render :new
    end
  end


private

  def category_params
    params.require(:category).permit(:name)
  end

end

postit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post # Associate the comment
    @comment.user = current_user
    
    if @comment.save
      flash[:notice] = "Your Comment was created"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end

  end
end

postit/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update]
  before_action :require_user, only: [:new, :create, :edit, :update]
  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = currrent_user

    if @post.save
      flash[:notice] = "You created a new post"
      redirect_to posts_path
    else
      # handles validations
      render :new
    end
  end

  def edit
    
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "You updated the post!"
      redirect_to post_path(@post)
    else
      render :edit #renders the edit view (not a redirect to edit_post_path)
    end
  end

  private
  
  def post_params
    params.require(:post).permit(:title, :url) #{title:'something', url: 'something'}
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

postit/app/controllers/sessions_controller.rb
class SessionsController <ApplicationController

  def new
  end

  def create
    #get a handle on the user (username)
    user = User.find_by(username: params[:username])

    #if user exists, call 'authenticate' and pass in the password
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you're logged in"
      redirect_to root_path
    else 
      flash[:error] = "Sorry, something's wrong with your username or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You're logged out."
    redirect_to root_path
  end

end

postit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)

    if @user.save
      flash[:notice] = "You have registered, now log in"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def users_params
    params.require(:user).permit(:username, :password)
  end

end

postit/app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(url)
    url.starts_with?('http') ? url : "http://#{url}"
  end

  def display_datetime(dt)
    dt.strftime ("%b %d, %Y %l:%M%P %Z")
  end
end

postit/app/views/categories/new.html.erb
<h5>Create a Category</h5>

<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.submit "Create Category", class: 'btn'  %>
<% end %>

postit/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

postit/app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  
  <% if logged_in? %>
    <li>
      Welcome, <%= current_user.username %>
    </li>
    <li>
      <%= link_to 'New Post', new_post_path %>
    </li>
    
    <li>
      <%= link_to 'New Category', new_category_path %>
    </li>

    <li>
      <%= link_to 'Logout', logout_path %>
    </li>
  <% else %>
    <li>
      <%= link_to 'Register', register_path %>
    </li>

    <li>
      <%= link_to 'Login', login_path %>
    </li>
  <% end %>
</ul>

postit/app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

postit/app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
</br>
  <%= f.label :url %>
  <%= f.text_field :url %>
</br>
  <%= f.submit @post.new_record? ? "Create Post" : "Update Post", class: 'btn' %>
<% end %>

postit/app/views/posts/edit.html.erb
<h4>Update Post</h4>

<%= render 'form' %>

postit/app/views/posts/index.html.erb
<h3>Welcome!</h3>

<ul>
  <% @posts.each do |post| %>
    <li> <%= link_to post.title, post %> 
      <small>
        [<%=link_to 'link', fix_url(post.url) %>] posted at 
        <%= display_datetime(post.created_at) %> 
        <%= link_to 'edit', edit_post_path(post) %>
      </small>

    </li>

  <% end %>
</ul>

postit/app/views/posts/new.html.erb
<h4>Creating a new Post object</h4>

<%= render 'form' %>

postit/app/views/posts/show.html.erb
<p>You're looking at <%= @post.title %></p>
<p>URL: <%= @post.url %></p>
<p>Description: <%= @post.description %></p> 

<p>

  <%= render 'shared/errors', obj: @comment %>

  <h5>Leave a Comment</h5>
    <%= form_for [@post, @comment] do |f| %> <!-- Gets mapped to Comments Controller Create action -->
      <%= f.text_area :body %>
      <br/>
      <%= f.submit "Create Comment", class: 'btn btn-primary'%>
    <% end %>


  <h5>Comments:</h5>
  <ol>
    <% @post.comments.each do |comment| %>
      <li><%= comment.body %></li>
    <% end %>
  </ol>

</p>

postit/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class = 'alert alert-error'>
    <%= obj.errors.full_messages.join(', ') %>
  </div>
<% end %>

postit/app/views/users/new.html.erb
<h5>Register</h5>

<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br/>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/>
  <%= f.submit "Register", class: 'btn btn-primary' %>
<% end %>